name: suru
services:
  prod:
    container_name: suru_api_prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:3000
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
  dev:
    container_name: suru_api_dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:3000
    env_file:
      - .env.local
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    container_name: suru_db
    image: postgres:latest
    environment:
      POSTGRES_USER: suru
      POSTGRES_PASSWORD: suru
      POSTGRES_DB: suru
    ports:
      - "9232:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
